### ISSUE TITLE
Answering your question in css file and a little bit more

### ISSUE THREAD

**Issue by farishkash** [BrandenLY/prj-rev-bwfs-dasmoto#1]
So lets talk about this first

```
div h2{
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

So this project isn't a monster size project.  Because h2 are in divs only, you do not need to put the div statement in front.  By the way you do not have to declare font family because you already did it for the whole page.

```
h2{
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Second as a matter of organized, (by the way this isn't critical of your project at all, it is excellent) and for your information, the way css is done by many but not all overarching css is done first.

What do I mean by that?  Body, p, headings, any direct element styling for basically.

Then css the rest is done in sections, so you had segment1 so matching with a comment, I would have css for segment1 first and so on.

Then when it comes to media queries I would follow the same pattern in them.

**Comment by BrandenLY** [comment]
Thank you, farishkash! This is all really helpful advice.
